### PR TITLE
added fastboot

### PR DESCRIPTION
**Pull request by davidpett**
it works without any config

### CODE REVIEW

**Comment by rwjblue** [comment]
Lets hold off on this until we land https://github.com/ember-engines/ember-engines.com/pull/5, I suspect we can use this PR as a way to push forward the lazy engine + fastboot story (as I believe there are a number of rough edge cases).

**Comment by trentmwillis** [comment]
Thanks for the initiative here! But as @rwjblue brings up, I imagine this will have some issues once we land #5, but I would very much like this to be a place to figure out the FastBoot + Lazy Engine story!

**Comment by trentmwillis** [comment]
Did some digging and I've identified two issues so far:

1. Apparently FastBoot builds [the app a second time](https://github.com/ember-fastboot/ember-cli-fastboot/blob/0f7658aa3187a7ec4f23c36d14a433d027cfa32f/lib/broccoli/fastboot-build.js#L72-L73) so we get an error from the `ManifestGenerator` about overwriting an existing field. Fixing this _should_ allow you to _build_ lazy Engines in FastBoot.

2. Bypassing the above, reveals that we need to properly load the manifest and lazy assets into the FastBoot sandbox (or else it throws an error at request time). Fixing this _should_ allow you to _run_ lazy Engines in FastBoot.

**Comment by kratiahuja** [comment]
@trentmwillis @rwjblue regarding the issue #2  that Trent pointed out, this [PR](https://github.com/ember-fastboot/fastboot/pull/97) that exposes a low level primitive to load lazy engines in sandbox should fix it.

My understanding of lazy engines is very very limited but wouldn't be there be another issue where an app that is running fastboot and using lazy engines will never send the correct engine to the browser? The reason being fastboot will send the index.html. So you will need to add the correct engine in index.html?

**Comment by villander** [comment]
This PR can be closed now with #39

**Comment by rwjblue** [comment]
Thank you all for your hard work!!

**Pull request closed without merging**
